//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.VisualStudio.ServiceReference.Platforms, version 16.0.31829.152
// 
namespace speechTherapist.ServiceReference2 {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="metupal", Namespace="http://schemas.datacontract.org/2004/07/model")]
    public partial class metupal : speechTherapist.ServiceReference2.baseEntity {
        
        private string communication_dateField;
        
        private string date_birthField;
        
        private string id_metupalField;
        
        private string kupat_cholimField;
        
        private string name_metupalField;
        
        private string notesField;
        
        private string phone_numberField;
        
        private string reason_turningField;
        
        private string statusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string communication_date {
            get {
                return this.communication_dateField;
            }
            set {
                if ((object.ReferenceEquals(this.communication_dateField, value) != true)) {
                    this.communication_dateField = value;
                    this.RaisePropertyChanged("communication_date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string date_birth {
            get {
                return this.date_birthField;
            }
            set {
                if ((object.ReferenceEquals(this.date_birthField, value) != true)) {
                    this.date_birthField = value;
                    this.RaisePropertyChanged("date_birth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id_metupal {
            get {
                return this.id_metupalField;
            }
            set {
                if ((object.ReferenceEquals(this.id_metupalField, value) != true)) {
                    this.id_metupalField = value;
                    this.RaisePropertyChanged("id_metupal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string kupat_cholim {
            get {
                return this.kupat_cholimField;
            }
            set {
                if ((object.ReferenceEquals(this.kupat_cholimField, value) != true)) {
                    this.kupat_cholimField = value;
                    this.RaisePropertyChanged("kupat_cholim");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name_metupal {
            get {
                return this.name_metupalField;
            }
            set {
                if ((object.ReferenceEquals(this.name_metupalField, value) != true)) {
                    this.name_metupalField = value;
                    this.RaisePropertyChanged("name_metupal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string notes {
            get {
                return this.notesField;
            }
            set {
                if ((object.ReferenceEquals(this.notesField, value) != true)) {
                    this.notesField = value;
                    this.RaisePropertyChanged("notes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string phone_number {
            get {
                return this.phone_numberField;
            }
            set {
                if ((object.ReferenceEquals(this.phone_numberField, value) != true)) {
                    this.phone_numberField = value;
                    this.RaisePropertyChanged("phone_number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string reason_turning {
            get {
                return this.reason_turningField;
            }
            set {
                if ((object.ReferenceEquals(this.reason_turningField, value) != true)) {
                    this.reason_turningField = value;
                    this.RaisePropertyChanged("reason_turning");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string status {
            get {
                return this.statusField;
            }
            set {
                if ((object.ReferenceEquals(this.statusField, value) != true)) {
                    this.statusField = value;
                    this.RaisePropertyChanged("status");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="baseEntity", Namespace="http://schemas.datacontract.org/2004/07/model")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(speechTherapist.ServiceReference2.treatment))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(speechTherapist.ServiceReference2.summingOfSeries))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(speechTherapist.ServiceReference2.problem))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(speechTherapist.ServiceReference2.problemForMetupal))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(speechTherapist.ServiceReference2.metupal))]
    public partial class baseEntity : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="treatment", Namespace="http://schemas.datacontract.org/2004/07/model")]
    public partial class treatment : speechTherapist.ServiceReference2.baseEntity {
        
        private int code_meatingField;
        
        private speechTherapist.ServiceReference2.metupal code_metupalField;
        
        private speechTherapist.ServiceReference2.summingOfSeries code_seriesField;
        
        private System.DateTime date_treatmentField;
        
        private string hour_treatmentField;
        
        private string how_paidField;
        
        private bool is_paidField;
        
        private int num_treatmentField;
        
        private string status_treatmentField;
        
        private string the_treatmentField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int code_meating {
            get {
                return this.code_meatingField;
            }
            set {
                if ((this.code_meatingField.Equals(value) != true)) {
                    this.code_meatingField = value;
                    this.RaisePropertyChanged("code_meating");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public speechTherapist.ServiceReference2.metupal code_metupal {
            get {
                return this.code_metupalField;
            }
            set {
                if ((object.ReferenceEquals(this.code_metupalField, value) != true)) {
                    this.code_metupalField = value;
                    this.RaisePropertyChanged("code_metupal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public speechTherapist.ServiceReference2.summingOfSeries code_series {
            get {
                return this.code_seriesField;
            }
            set {
                if ((object.ReferenceEquals(this.code_seriesField, value) != true)) {
                    this.code_seriesField = value;
                    this.RaisePropertyChanged("code_series");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime date_treatment {
            get {
                return this.date_treatmentField;
            }
            set {
                if ((this.date_treatmentField.Equals(value) != true)) {
                    this.date_treatmentField = value;
                    this.RaisePropertyChanged("date_treatment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string hour_treatment {
            get {
                return this.hour_treatmentField;
            }
            set {
                if ((object.ReferenceEquals(this.hour_treatmentField, value) != true)) {
                    this.hour_treatmentField = value;
                    this.RaisePropertyChanged("hour_treatment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string how_paid {
            get {
                return this.how_paidField;
            }
            set {
                if ((object.ReferenceEquals(this.how_paidField, value) != true)) {
                    this.how_paidField = value;
                    this.RaisePropertyChanged("how_paid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool is_paid {
            get {
                return this.is_paidField;
            }
            set {
                if ((this.is_paidField.Equals(value) != true)) {
                    this.is_paidField = value;
                    this.RaisePropertyChanged("is_paid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int num_treatment {
            get {
                return this.num_treatmentField;
            }
            set {
                if ((this.num_treatmentField.Equals(value) != true)) {
                    this.num_treatmentField = value;
                    this.RaisePropertyChanged("num_treatment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string status_treatment {
            get {
                return this.status_treatmentField;
            }
            set {
                if ((object.ReferenceEquals(this.status_treatmentField, value) != true)) {
                    this.status_treatmentField = value;
                    this.RaisePropertyChanged("status_treatment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string the_treatment {
            get {
                return this.the_treatmentField;
            }
            set {
                if ((object.ReferenceEquals(this.the_treatmentField, value) != true)) {
                    this.the_treatmentField = value;
                    this.RaisePropertyChanged("the_treatment");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="summingOfSeries", Namespace="http://schemas.datacontract.org/2004/07/model")]
    public partial class summingOfSeries : speechTherapist.ServiceReference2.baseEntity {
        
        private int code_seriesField;
        
        private System.DateTime date_testField;
        
        private string discrabtion_first_stateField;
        
        private bool is_formField;
        
        private bool is_testingField;
        
        private speechTherapist.ServiceReference2.metupal metupalField;
        
        private int num_minutesField;
        
        private int number_meatingField;
        
        private int number_meating_certifiedField;
        
        private int priceForMeatingField;
        
        private string the_goalsField;
        
        private string tretmentField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int code_series {
            get {
                return this.code_seriesField;
            }
            set {
                if ((this.code_seriesField.Equals(value) != true)) {
                    this.code_seriesField = value;
                    this.RaisePropertyChanged("code_series");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime date_test {
            get {
                return this.date_testField;
            }
            set {
                if ((this.date_testField.Equals(value) != true)) {
                    this.date_testField = value;
                    this.RaisePropertyChanged("date_test");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string discrabtion_first_state {
            get {
                return this.discrabtion_first_stateField;
            }
            set {
                if ((object.ReferenceEquals(this.discrabtion_first_stateField, value) != true)) {
                    this.discrabtion_first_stateField = value;
                    this.RaisePropertyChanged("discrabtion_first_state");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool is_form {
            get {
                return this.is_formField;
            }
            set {
                if ((this.is_formField.Equals(value) != true)) {
                    this.is_formField = value;
                    this.RaisePropertyChanged("is_form");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool is_testing {
            get {
                return this.is_testingField;
            }
            set {
                if ((this.is_testingField.Equals(value) != true)) {
                    this.is_testingField = value;
                    this.RaisePropertyChanged("is_testing");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public speechTherapist.ServiceReference2.metupal metupal {
            get {
                return this.metupalField;
            }
            set {
                if ((object.ReferenceEquals(this.metupalField, value) != true)) {
                    this.metupalField = value;
                    this.RaisePropertyChanged("metupal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int num_minutes {
            get {
                return this.num_minutesField;
            }
            set {
                if ((this.num_minutesField.Equals(value) != true)) {
                    this.num_minutesField = value;
                    this.RaisePropertyChanged("num_minutes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int number_meating {
            get {
                return this.number_meatingField;
            }
            set {
                if ((this.number_meatingField.Equals(value) != true)) {
                    this.number_meatingField = value;
                    this.RaisePropertyChanged("number_meating");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int number_meating_certified {
            get {
                return this.number_meating_certifiedField;
            }
            set {
                if ((this.number_meating_certifiedField.Equals(value) != true)) {
                    this.number_meating_certifiedField = value;
                    this.RaisePropertyChanged("number_meating_certified");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int priceForMeating {
            get {
                return this.priceForMeatingField;
            }
            set {
                if ((this.priceForMeatingField.Equals(value) != true)) {
                    this.priceForMeatingField = value;
                    this.RaisePropertyChanged("priceForMeating");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string the_goals {
            get {
                return this.the_goalsField;
            }
            set {
                if ((object.ReferenceEquals(this.the_goalsField, value) != true)) {
                    this.the_goalsField = value;
                    this.RaisePropertyChanged("the_goals");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tretment {
            get {
                return this.tretmentField;
            }
            set {
                if ((object.ReferenceEquals(this.tretmentField, value) != true)) {
                    this.tretmentField = value;
                    this.RaisePropertyChanged("tretment");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="problem", Namespace="http://schemas.datacontract.org/2004/07/model")]
    public partial class problem : speechTherapist.ServiceReference2.baseEntity {
        
        private int code_problemField;
        
        private string name_problemField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int code_problem {
            get {
                return this.code_problemField;
            }
            set {
                if ((this.code_problemField.Equals(value) != true)) {
                    this.code_problemField = value;
                    this.RaisePropertyChanged("code_problem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name_problem {
            get {
                return this.name_problemField;
            }
            set {
                if ((object.ReferenceEquals(this.name_problemField, value) != true)) {
                    this.name_problemField = value;
                    this.RaisePropertyChanged("name_problem");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="problemForMetupal", Namespace="http://schemas.datacontract.org/2004/07/model")]
    public partial class problemForMetupal : speechTherapist.ServiceReference2.baseEntity {
        
        private speechTherapist.ServiceReference2.metupal metupalField;
        
        private string notesField;
        
        private speechTherapist.ServiceReference2.problem problemField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public speechTherapist.ServiceReference2.metupal metupal {
            get {
                return this.metupalField;
            }
            set {
                if ((object.ReferenceEquals(this.metupalField, value) != true)) {
                    this.metupalField = value;
                    this.RaisePropertyChanged("metupal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string notes {
            get {
                return this.notesField;
            }
            set {
                if ((object.ReferenceEquals(this.notesField, value) != true)) {
                    this.notesField = value;
                    this.RaisePropertyChanged("notes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public speechTherapist.ServiceReference2.problem problem {
            get {
                return this.problemField;
            }
            set {
                if ((object.ReferenceEquals(this.problemField, value) != true)) {
                    this.problemField = value;
                    this.RaisePropertyChanged("problem");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllMetupal", ReplyAction="http://tempuri.org/IService1/GetAllMetupalResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<speechTherapist.ServiceReference2.metupal>> GetAllMetupalAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateMetupal", ReplyAction="http://tempuri.org/IService1/UpdateMetupalResponse")]
        System.Threading.Tasks.Task UpdateMetupalAsync(speechTherapist.ServiceReference2.metupal m1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteMetupal", ReplyAction="http://tempuri.org/IService1/DeleteMetupalResponse")]
        System.Threading.Tasks.Task DeleteMetupalAsync(speechTherapist.ServiceReference2.metupal m2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetMetupalByStatusAndKupa", ReplyAction="http://tempuri.org/IService1/GetMetupalByStatusAndKupaResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<speechTherapist.ServiceReference2.metupal>> GetMetupalByStatusAndKupaAsync(string s1, string s2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTreatmentByName", ReplyAction="http://tempuri.org/IService1/GetTreatmentByNameResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<speechTherapist.ServiceReference2.treatment>> GetTreatmentByNameAsync(string s3);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddMetupal", ReplyAction="http://tempuri.org/IService1/AddMetupalResponse")]
        System.Threading.Tasks.Task<int> AddMetupalAsync(speechTherapist.ServiceReference2.metupal m3);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddTreatment", ReplyAction="http://tempuri.org/IService1/AddTreatmentResponse")]
        System.Threading.Tasks.Task AddTreatmentAsync(speechTherapist.ServiceReference2.treatment t1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateTreatment", ReplyAction="http://tempuri.org/IService1/UpdateTreatmentResponse")]
        System.Threading.Tasks.Task UpdateTreatmentAsync(speechTherapist.ServiceReference2.treatment t2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteTreatment", ReplyAction="http://tempuri.org/IService1/DeleteTreatmentResponse")]
        System.Threading.Tasks.Task DeleteTreatmentAsync(speechTherapist.ServiceReference2.treatment t3);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTreatment", ReplyAction="http://tempuri.org/IService1/GetTreatmentResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<speechTherapist.ServiceReference2.treatment>> GetTreatmentAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetProblems", ReplyAction="http://tempuri.org/IService1/GetProblemsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<speechTherapist.ServiceReference2.problem>> GetProblemsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetProblemForMetupalByNameMetupal", ReplyAction="http://tempuri.org/IService1/GetProblemForMetupalByNameMetupalResponse")]
        System.Threading.Tasks.Task<speechTherapist.ServiceReference2.problemForMetupal> GetProblemForMetupalByNameMetupalAsync(string Name);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : speechTherapist.ServiceReference2.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<speechTherapist.ServiceReference2.IService1>, speechTherapist.ServiceReference2.IService1 {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public Service1Client() : 
                base(Service1Client.GetDefaultBinding(), Service1Client.GetDefaultEndpointAddress()) {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IService1.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), Service1Client.GetEndpointAddress(endpointConfiguration)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), remoteAddress) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<speechTherapist.ServiceReference2.metupal>> GetAllMetupalAsync() {
            return base.Channel.GetAllMetupalAsync();
        }
        
        public System.Threading.Tasks.Task UpdateMetupalAsync(speechTherapist.ServiceReference2.metupal m1) {
            return base.Channel.UpdateMetupalAsync(m1);
        }
        
        public System.Threading.Tasks.Task DeleteMetupalAsync(speechTherapist.ServiceReference2.metupal m2) {
            return base.Channel.DeleteMetupalAsync(m2);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<speechTherapist.ServiceReference2.metupal>> GetMetupalByStatusAndKupaAsync(string s1, string s2) {
            return base.Channel.GetMetupalByStatusAndKupaAsync(s1, s2);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<speechTherapist.ServiceReference2.treatment>> GetTreatmentByNameAsync(string s3) {
            return base.Channel.GetTreatmentByNameAsync(s3);
        }
        
        public System.Threading.Tasks.Task<int> AddMetupalAsync(speechTherapist.ServiceReference2.metupal m3) {
            return base.Channel.AddMetupalAsync(m3);
        }
        
        public System.Threading.Tasks.Task AddTreatmentAsync(speechTherapist.ServiceReference2.treatment t1) {
            return base.Channel.AddTreatmentAsync(t1);
        }
        
        public System.Threading.Tasks.Task UpdateTreatmentAsync(speechTherapist.ServiceReference2.treatment t2) {
            return base.Channel.UpdateTreatmentAsync(t2);
        }
        
        public System.Threading.Tasks.Task DeleteTreatmentAsync(speechTherapist.ServiceReference2.treatment t3) {
            return base.Channel.DeleteTreatmentAsync(t3);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<speechTherapist.ServiceReference2.treatment>> GetTreatmentAsync() {
            return base.Channel.GetTreatmentAsync();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<speechTherapist.ServiceReference2.problem>> GetProblemsAsync() {
            return base.Channel.GetProblemsAsync();
        }
        
        public System.Threading.Tasks.Task<speechTherapist.ServiceReference2.problemForMetupal> GetProblemForMetupalByNameMetupalAsync(string Name) {
            return base.Channel.GetProblemForMetupalByNameMetupalAsync(Name);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService1)) {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService1)) {
                return new System.ServiceModel.EndpointAddress("http://localhost:8733/Design_Time_Addresses/sharat_speech_therapist/Service1/");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding() {
            return Service1Client.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IService1);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress() {
            return Service1Client.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IService1);
        }
        
        public enum EndpointConfiguration {
            
            BasicHttpBinding_IService1,
        }
    }
}
